<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>41859b46-94e4-44a9-a7f9-6e73ce2cacef</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.1.0" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.3.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.3.0" />
    <PackageReference Include="Azure.Identity" Version="1.17.0" />
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.48.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TravelPlanner.Shared\TravelPlanner.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\src\Azure.AppService.AgentDashboard\Azure.AppService.AgentDashboard.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="run.cmd">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
